/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CloudflareAccountId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CloudflareKv": {
      "id": string
      "type": "sst.cloudflare.Kv"
    }
    "Database": {
      "token": string
      "type": "sst.sst.Linkable"
      "url": string
    }
    "DiscordBotId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordBotSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordServerId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAuthDiscordId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAuthDiscordSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAuthTwitchId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAuthTwitchSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SomeFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}